### PR TITLE
Perform more rigorous validation on the group and feature names

### PR DESCRIPTION
**Pull request by moddular**

### CODE REVIEW

**Comment by dazoakley** [comment]
Looks good to me :+1:

Maybe add some info to the HISTORY file and bump the version number so we can have this as a patch release?

**Comment by moddular** [comment]
Sure, no problem. Would you like the version bump squashed into this commit or separately?

**Comment by dazoakley** [comment]
Maybe separate?

**Comment by moddular** [comment]
👍

**Comment by dazoakley** [comment]
👍

**Pull request merged**
