### PR TITLE
Bandiera release 3.2.0

### PR DESCRIPTION
**Pull request by dazoakley**
* Include the new date range feature logic in a release
* Update the base ruby version to 2.4.1
* Update dependencies

### CODE REVIEW

**Comment by mattrayner** [comment]
Just to ask, once this is merged, what's the process for updating docker hub?

**Comment by baob** [comment]
Before merging, we should really have a matrix build on travis to ensure we’re support both the new version you’ve introduced and the older one (2.3.1).

**Comment by dazoakley** [comment]
@mattrayner the docker build is managed via my "fork" (under dazoakley). But basically as soon as this is merged and tagged it'll be automatically built and released on docker hub.

@baob good idea with the build matrix - will do that this evening :+1:

**Comment by dazoakley** [comment]
In fact, as I have internet on the train - it's done 😄

**Comment by baob** [comment]
👍  LGTM

**Pull request merged**
